@startmindmap ss
* Debian
** Ubuntu
*** Linux Mint
*** Kubuntu
*** Lubuntu
*** KDE Neon
--[#lightgreen] LMDE
** SolydXK
** SteamOS
** Raspbian with a very long name
*** <s>Raspmbc => OSMC </s> 
*** <s>Raspyfi</s> => Volumio


@endmindmap
