@startuml ad
start
partition #lightGreen 登录中 {
:"触发登录";
if ("一键登录是否可用") then (true)
    :展示一键登录;
    if ("是否点击一键登录") then (yes)
        :"一键登录成功";
    else
        if ("是否验证码登录") then (yes)
            :"验证码登录";
        else (no)
            :"第三方登录";
        endif
    endif
    :"登陆成功";
endif
}

partition 登录后 {
if ("条件4判断") then (yes)
:"条件4成立的动作";
else
    if ("条件5判断") then (yes)
        :"条件5成立时的动作";
    else (no)
        :"条件5不成立时的动作";
    endif
endif
}
stop
@enduml
