@startwbs adprojects
* 项目关键路径拆解：
** 看到/操作后，减少负体验
***	素材质量（视屏图片文案）
***	广告主不喜欢拼多多、同城交友、某个游戏
***	广告频繁
***	广告重复出现
***	操作前的预期和现实不符，如何减弱？
*** 负体验产生后，帮助用户阻断缓解更负的体验
** 用z户看到广告很烦，不去反馈
*** 直接就关掉了（是否能监控到用户是因为广告而退出的，下次就给该用户更少的广告或者引导用户反）
*** 直接卸载
*** 直接划走（这类耐受度高，可不管控，不要再过分薅即可）
*** 提供用户反馈路径：负反馈弹窗信息持续优化引导用户来反馈&传达“反馈是有效的”
** 反馈后的退避策略 （核心问题参考：「广告展示过多」访谈提纲）
*** 帮助反馈处理及时性、监控、处理进度传达
*** 异常行为监控和前置拦截、报警
*** 广告内容（素材、文案）审核标准细化？
*** 其他广告体验优化


@endwbs